Algoritmo "A) Crie um algoritmo em que o usuário entre com 5 valores e mostre os valores digitados"

Var
vetorDeCincoPosicoes: vetor[1..5] de inteiro
contador: inteiro

Inicio
escreval("Digite 5 valores: ")

para contador de 1 ate 5 faca
     leia(vetorDeCincoPosicoes[contador])
fimpara

escreval("") // Para identação
escreval("Os valores digitados foram: ")

para contador de 1 ate 5 faca
     escreval(vetorDeCincoPosicoes[contador])
fimpara

Fimalgoritmo